require 'rubygems'
require 'bundler/setup'

require 'rspec/core/rake_task'

desc 'Run RSpec'
RSpec::Core::RakeTask.new do |spec|
  spec.pattern = 'spoj/**/*_spec.rb'
end

task :default => :spec